import{S as h,a as y,i as l}from"./assets/vendor-B3Lscd_h.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const b=new h(".gallery a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250});function L(e){const r=document.querySelector(".gallery"),n=e.map(({webformatURL:a,largeImageURL:t,tags:o,likes:s,views:p,comments:m,downloads:g})=>`
      <li class="gallery-item">
        <a href="${t}" data-title="${o}">
          <img src="${a}" alt="${o}" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${s}</p>
          <p><b>Views:</b> ${p}</p>
          <p><b>Comments:</b> ${m}</p>
          <p><b>Downloads:</b> ${g}</p>
        </div>
      </li>
    `).join("");r.insertAdjacentHTML("beforeend",n),b.refresh()}function w(){const e=document.querySelector(".gallery");e.innerHTML=""}const d=document.querySelector(".loader");function S(){d.classList.add("is-visible")}function v(){d.classList.remove("is-visible")}const q="50473817-3aff601f70e503f6e91238097",P="https://pixabay.com/api/",$=15;async function B(e,r=1){return(await y.get(P,{params:{key:q,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:$}})).data}const E=document.querySelector("#search-form"),x=document.querySelector(".gallery"),M=document.querySelector(".load-more");let c="",i=1,u=0;const O=new SimpleLightbox(".gallery a");E.addEventListener("submit",async e=>{if(e.preventDefault(),c=e.target.elements["search-text"].value.trim(),!c){l.warning({message:"Please enter a search term!",position:"topRight"});return}i=1,w(),hideLoadMoreButton(),await f()});M.addEventListener("click",async()=>{i+=1,await f()});async function f(){try{S();const e=await B(c,i);if(u=e.totalHits,e.hits.length===0&&i===1){l.error({message:"Sorry, no images found.",position:"topRight"});return}L(e.hits),O.refresh(),document.querySelectorAll(".gallery a").length>=u?(hideLoadMoreButton(),l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):showLoadMoreButton(),i>1&&R()}catch(e){l.error({message:"Oops! Something went wrong.",position:"topRight"}),console.error(e)}finally{v()}}function R(){const{height:e}=x.firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
