import{S as h,a as b,i as c}from"./assets/vendor-B3Lscd_h.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function i(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=i(t);fetch(t.href,o)}})();const L=new h(".gallery a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250});function w(e){const r=document.querySelector(".gallery"),i=e.map(({webformatURL:a,largeImageURL:t,tags:o,likes:n,views:p,comments:g,downloads:y})=>`
      <li class="gallery-item">
        <a href="${t}" data-title="${o}">
          <img src="${a}" alt="${o}" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${n}</p>
          <p><b>Views:</b> ${p}</p>
          <p><b>Comments:</b> ${g}</p>
          <p><b>Downloads:</b> ${y}</p>
        </div>
      </li>
    `).join("");r.insertAdjacentHTML("beforeend",i),L.refresh()}function S(){const e=document.querySelector(".gallery");e.innerHTML=""}const d=document.querySelector(".loader");function v(){d.classList.add("is-visible")}function q(){d.classList.remove("is-visible")}function P(){document.querySelector(".load-more").classList.remove("hidden")}function f(){document.querySelector(".load-more").classList.add("hidden")}const E="50473817-3aff601f70e503f6e91238097",$="https://pixabay.com/api/",B=15;async function O(e,r=1){return(await b.get($,{params:{key:E,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:B}})).data}const R=document.querySelector(".form"),A=document.querySelector(".gallery"),I=document.querySelector(".load-more");let l="",s=1,u=0;R.addEventListener("submit",async e=>{if(e.preventDefault(),l=e.target.elements["search-text"].value.trim(),!l){c.warning({message:"Please enter a search term!",position:"topRight"});return}s=1,S(),f(),await m()});I.addEventListener("click",async()=>{s+=1,await m()});async function m(){try{v();const e=await O(l,s);if(u=e.totalHits,e.hits.length===0&&s===1){c.error({message:"Sorry, no images found.",position:"topRight"});return}w(e.hits),document.querySelectorAll(".gallery a").length>=u?(f(),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):P(),s>1&&M()}catch(e){c.error({message:"Oops! Something went wrong.",position:"topRight"}),console.error(e)}finally{q()}}function M(){const{height:e}=A.firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
